config/routes.rb
Manticore::Application.routes.draw do

  resources :characters do
    resources :statistics
  end

  root :to => "characters#index"

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_one :statistic
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
    @statistic = (@character.statistic || @character.build_statistic)
  end

  def new
    @character = Character.new
  end

  def edit
    @character = Character.find(params[:id])
  end

  def create
    @character = Character.new(params[:character])
    if @character.save
      redirect_to(@character, :notice => 'Character was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @character = Character.find(params[:id])
    if @character.update_attributes(params[:character])
      redirect_to(@character, :notice => 'Character was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to(characters_url)
  end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  def new
    @character = Character.find(params[:character_id])
    @statistic = @character.create_statistic(params[:statistic])
  end

  def edit
    @character = Character.find(params[:character_id])
    @statistic = @character.statistic
  end

  def create
    @character = Character.find(params[:character_id])
    @statistic = @character.create_statistic(params[:statistic])
    redirect_to character_path(@character), :notice => 'Statistic was successfully created.'
  end

  def update
    @character = Character.find(params[:character_id])
    @statistic = @character.statistic
    if @statistic.update_attributes(params[:statistic])
      redirect_to character_path(@character), :notice => 'Statistic was successfully updated.'
    else
      render :action => "edit"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/_statistic_form.html.erb
<%= form_for ([@character, @statistic]) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from                 
        being saved:</h2>

      <ul>
        <% @statistic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :strength %><br />
    <%= f.text_field :strength %>
    <div class="field">
      <%= f.label :charisma %><br />
      <%= f.text_field :charisma %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Strength:</b>
  <%= @statistic.strength || 'Not set' %>
</p>

<p>
  <b>Charisma:</b>
  <%= @statistic.charisma || 'Not set' %>
</p>

<% if @statistic.new_record? %>
  <%= link_to 'Add Statistics', new_character_statistic_path(@character) %>
<% else %>
  <%= link_to 'Edit Statistics', edit_character_statistic_path(@character,@statistic) %>
<% end %>

<%#= render "statistics/form" %>
<hr/>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manticore</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/statistics/_form.html.erb
<%= form_for([@character, @statistic]) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% @statistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :strength %><br />
    <%= f.text_field :strength %>
  </div>
  <div class="field">
    <%= f.label :charisma %><br />
    <%= f.text_field :charisma %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing statistic for <%= @character.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', character_path(@character) %>

app/views/statistics/index.html.erb
<h1>Listing statistics</h1>

<table>
  <tr>
    <th>References</th>
    <th>Strength</th>
    <th>Charisma</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statistics.each do |statistic| %>
  <tr>
    <td><%= statistic.references %></td>
    <td><%= statistic.strength %></td>
    <td><%= statistic.charisma %></td>
    <td><%= link_to 'Show', statistic %></td>
    <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
    <td><%= link_to 'Destroy', statistic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New statistic for <%= @character.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', character_path(@character) %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>References:</b>
  <%= @statistic.references %>
</p>

<p>
  <b>Strength:</b>
  <%= @statistic.strength %>
</p>

<p>
  <b>Charisma:</b>
  <%= @statistic.charisma %>
</p>


<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>